### ISSUE TITLE
Auto-find inventory

### ISSUE THREAD

**Issue by jedahan** [inn3rvoice/inventory_alpha#1]
Idea for figuring out coordinates automatically. 

Random sample the bottom right quadrant of the screen until we find an item in the inventory. Scan pixels up and down, left and right to determine width and height. Then only need to check maximum 105 locations. No need for folks to mess with resolution settings

**Comment by jedahan** [comment]
A simpler but more fragile solution - use opencv to find the location of the gold icon to get the bottom left corner coordinates of inventory, and the sort icon to get the top right.

**Comment by inn3rvoice** [comment]
Hey jedahan, thanks for the feedback and good ideas! The thing is there are only a set handful number of resolutions that exist and since I have most of them now thanks to the community, once those are set they won't change so they can be hardcoded as constants.

**Comment by jedahan** [comment]
Ahh, that's simpler :)
